# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  agent1

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'sshvm'
    sourceFolder: '$(agent.builddirectory)'
    contents: '**/*.jar'
    targetFolder: '/home/azureuser/azuredevops'
    readyTimeout: '20000'
    overwrite: true
    flattenFolders: true
- task: SSH@0
  inputs:
    sshEndpoint: 'sshvm'
    runOptions: 'commands'
    commands: 'sudo docker build -t purushothamareddy/ssh .'
    readyTimeout: '20000'